name: Parallel Test Build
on: push
jobs:
  loginTest-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:loginTest

      - name: Cypress Test Report
        uses: actions/upload-artifact@v3
        with:
          name: Mochawesome HTML Report - Login Test          
          path: cypress/reports/html

  registerTest-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:registerTest

      - name: Cypress Test Report
        uses: actions/upload-artifact@v3
        with:
          name: Mochawesome HTML Report - Reg Flow
          path: cypress/reports/html


  profileTest-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:profileTest

      - name: Cypress Test Report
        uses: actions/upload-artifact@v3
        with:
          name: Mochawesome HTML Report - profileTest Flow
          path: cypress/reports/html
